USE [ArenaDB]
GO

/****** Object:  StoredProcedure [dbo].[cust_sp_salc_rc_save_client]    Script Date: 04/13/2012 13:43:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



-- =============================================
-- Author:		Den Boice
-- Create date: 02/08/2012
-- Description:	Save Resource Center client data
-- =============================================
CREATE PROCEDURE [dbo].[cust_sp_salc_rc_save_client]
	-- Add the parameters for the stored procedure here
	@ClientId int,
	@UserID varchar(50),
	@NumAdults int,
	@NumChildren int,
	@County varchar(50),
	@HelpRequested int,
	@Notes text,
	@NickName varchar(50),
	@FirstName varchar(50),
	@MiddleName varchar(50),
	@LastName varchar(50),
	@Suffix varchar(10),
	@Birthday date,
	@Gender varchar(1),
	@Email varchar(50),
	@Street varchar(50),
	@City varchar(50),
	@State varchar(2),
	@PostalCode varchar(10),
	@SSN varchar(11),
	@SchoolDistrict varchar(50),
	@IncomeEmployment decimal,
	@IncomeMFIP decimal,
	@IncomeMA decimal,
	@IncomeChildSupport decimal,
	@IncomeUnemployment decimal,
	@IncomeSSISSDI decimal,
	@IncomeOther decimal,
	@CashOnHand decimal,
	@IssuesOfNote int,
	@LastDateWorked date,
	@MaritalStatus int,
	@DriversLicense int,
	@EBT int,
	@FoodSupport decimal,
	@AssistanceApplied date,
	@FoodShelf varchar(50),
	@FoodShelfVisit date,
	@CaseMgr1Name varchar(50),
	@CaseMgr1Agency varchar(50),
	@CaseMgr1Phone varchar(20),
	@CaseMgr1Notes varchar(50),
	@CaseMgr2Name varchar(50),
	@CaseMgr2Agency varchar(50),
	@CaseMgr2Phone varchar(20),
	@CaseMgr2Notes varchar(50),
	@EmgAssist1Agency varchar(50),
	@EmgAssist1CaseMgr varchar(50),
	@EmgAssist1Phone varchar(20),
	@EmgAssist1Date date,
	@EmgAssist1Amount decimal,
	@EmgAssist1Status int,
	@EmgAssist2Agency varchar(50),
	@EmgAssist2CaseMgr varchar(50),
	@EmgAssist2Phone varchar(20),
	@EmgAssist2Date date,
	@EmgAssist2Amount decimal,
	@EmgAssist2Status int,
	@PastShelter int,
	@PastShelterDate date,
	@PastUnsheltered int,
	@PastUnshelteredDate date,
	@PastChemical int,
	@PastChemicalDate date,
	@PastTransitional int,
	@PastTransitionalDate date,
	@PastDoubled int,
	@PastDoubledDate date,
	@PastEviction int,
	@PastEvictionDate date,
	@PastForeclosure int,
	@PastForeclosureDate date,
	@PhoneHome varchar(20),
	@PhoneWork varchar(20),
	@PhoneMobile varchar(20),
	@PhoneOther varchar(20),
	@EmpFreq int,
	@EmpDate date,
	@MFIPDay int,
	@ChildSupportDate date,
	@OtherSourcesDate date,
	@OrganizationId int,
	@Message varchar(50),
	@Flag int,
	@ID int OUTPUT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
    
    DECLARE @UpdateDateTime DateTime SET @UpdateDateTime = GETDATE()
    
    IF NOT EXISTS(
		SELECT * FROM cust_salc_rc_clients
		WHERE [id] = @ClientId
		)
	BEGIN
		INSERT INTO cust_salc_rc_clients
		(
			[date_created],
			[date_updated],
			[created_by],
			[updated_by],
			[num_adults],
			[num_children],
			[county_of_origin],
			[help_requested],
			[notes],
			[nick_name],
			[first_name],
			[middle_name],
			[last_name],
			[suffix],
			[birthday],
			[gender],
			[email],
			[street_address],
			[city],
			[state],
			[postal_code],
			[ssn],
			[school_district],
			[income_employment],
			[income_unemployment],
			[income_mfip],
			[income_ma],
			[income_childsupport],
			[income_ssissdi],
			[income_other],
			[cash_on_hand],
			[issues],
			[last_date_worked],
			[mstatus],
			[dlicense],
			[ebt],
			[food_support],
			[applied_assistance],
			[food_shelf],
			[food_shelf_visit],
			[casemgr_1_name],
			[casemgr_1_agency],
			[casemgr_1_phone],
			[casemgr_1_notes],
			[casemgr_2_name],
			[casemgr_2_agency],
			[casemgr_2_phone],
			[casemgr_2_notes],
			[emgassist_1_agency],
			[emgassist_1_casemgr],
			[emgassist_1_phone],
			[emgassist_1_date],
			[emgassist_1_amount],
			[emgassist_1_status],
			[emgassist_2_agency],
			[emgassist_2_casemgr],
			[emgassist_2_phone],
			[emgassist_2_date],
			[emgassist_2_amount],
			[emgassist_2_status],
			[past_shelter],
			[past_shelter_date],
			[past_unsheltered],
			[past_unsheltered_date],
			[past_chemical],
			[past_chemical_date],
			[past_transitional],
			[past_transitional_date],
			[past_doubled],
			[past_doubled_date],
			[past_eviction],
			[past_eviction_date],
			[past_foreclosure],
			[past_foreclosure_date],
			[phone_home],
			[phone_work],
			[phone_mobile],
			[phone_other],
			[employment_frequency],
			[employment_date],
			[mfip_day],
			[childsupport_date],
			[othersources_date],
			[message],
			[flag],
			[organization_id]
		)
		values
		(
			@UpdateDateTime,
			@UpdateDateTime,
			@UserID,
			@UserID,
			@NumAdults,
			@NumChildren,
			@County,
			@HelpRequested,
			@Notes,
			@NickName,
			@FirstName,
			@MiddleName,
			@LastName,
			@Suffix,
			@Birthday,
			@Gender,
			@Email,
			@Street,
			@City,
			@State,
			@PostalCode,
			@SSN,
			@SchoolDistrict,
			@IncomeEmployment,
			@IncomeUnemployment,
			@IncomeMFIP,
			@IncomeMA,
			@IncomeChildSupport,
			@IncomeSSISSDI,
			@IncomeOther,
			@CashOnHand,
			@IssuesOfNote,
			@LastDateWorked,
			@MaritalStatus,
			@DriversLicense,
			@EBT,
			@FoodSupport,
			@AssistanceApplied,
			@FoodShelf,
			@FoodShelfVisit,
			@CaseMgr1Name,
			@CaseMgr1Agency,
			@CaseMgr1Phone,
			@CaseMgr1Notes,
			@CaseMgr2Name,
			@CaseMgr2Agency,
			@CaseMgr2Phone,
			@CaseMgr2Notes,
			@EmgAssist1Agency,
			@EmgAssist1CaseMgr,
			@EmgAssist1Phone,
			@EmgAssist1Date,
			@EmgAssist1Amount,
			@EmgAssist1Status,
			@EmgAssist2Agency,
			@EmgAssist2CaseMgr,
			@EmgAssist2Phone,
			@EmgAssist2Date,
			@EmgAssist2Amount,
			@EmgAssist2Status,
			@PastShelter,
			@PastShelterDate,
			@PastUnsheltered,
			@PastUnshelteredDate,
			@PastChemical,
			@PastChemicalDate,
			@PastTransitional,
			@PastTransitionalDate,
			@PastDoubled,
			@PastDoubledDate,
			@PastEviction,
			@PastEvictionDate,
			@PastForeclosure,
			@PastForeclosureDate,
			@PhoneHome,
			@PhoneWork,
			@PhoneMobile,
			@PhoneOther,
			@EmpFreq,
			@EmpDate,
			@MFIPDay,
			@ChildSupportDate,
			@OtherSourcesDate,
			@Message,
			@Flag,
			@OrganizationId
		)
		SET @ID = @@IDENTITY
	END
	ELSE
	BEGIN
		UPDATE cust_salc_rc_clients Set
			[date_updated] = @UpdateDateTime,
			[updated_by] = @UserID,
			[num_adults] = @NumAdults,
			[num_children] = @NumChildren,
			[county_of_origin] = @County,
			[help_requested] = @HelpRequested,
			[notes] = @Notes,
			[nick_name] = @NickName,
			[first_name] = @FirstName,
			[middle_name] = @MiddleName,
			[last_name] = @LastName,
			[suffix] = @Suffix,
			[birthday] = @Birthday,
			[gender] = @Gender,
			[email] = @Email,
			[street_address] = @Street,
			[city] = @City,
			[state] = @State,
			[postal_code] = @PostalCode,
			[ssn] = @SSN,
			[school_district] = @SchoolDistrict,
			[income_employment] = @IncomeEmployment,
			[income_unemployment] = @IncomeUnemployment,
			[income_mfip] = @IncomeMFIP,
			[income_ma] = @IncomeMA,
			[income_childsupport] = @IncomeChildSupport,
			[income_ssissdi] = @IncomeSSISSDI,
			[income_other] = @IncomeOther,
			[cash_on_hand] = @CashOnHand,
			[issues] = @IssuesOfNote,
			[last_date_worked] = @LastDateWorked,
			[mstatus] = @MaritalStatus,
			[dlicense] = @DriversLicense,
			[ebt] = @EBT,
			[food_support] = @FoodSupport,
			[applied_assistance] = @AssistanceApplied,
			[food_shelf] = @FoodShelf,
			[food_shelf_visit] = @FoodShelfVisit,
			[casemgr_1_name] = @CaseMgr1Name,
			[casemgr_1_agency] = @CaseMgr1Agency,
			[casemgr_1_phone] = @CaseMgr1Phone,
			[casemgr_1_notes] = @CaseMgr1Notes,
			[casemgr_2_name] = @CaseMgr2Name,
			[casemgr_2_agency] = @CaseMgr2Agency,
			[casemgr_2_phone] = @CaseMgr2Phone,
			[casemgr_2_notes] = @CaseMgr2Notes,
			[emgassist_1_agency] = @EmgAssist1Agency,
			[emgassist_1_casemgr] = @EmgAssist1CaseMgr,
			[emgassist_1_phone] = @EmgAssist1Phone,
			[emgassist_1_date] = @EmgAssist1Date,
			[emgassist_1_amount] = @EmgAssist1Amount,
			[emgassist_1_status] = @EmgAssist1Status,
			[emgassist_2_agency] = @EmgAssist2Agency,
			[emgassist_2_casemgr] = @EmgAssist2CaseMgr,
			[emgassist_2_phone] = @EmgAssist2Phone,
			[emgassist_2_date] = @EmgAssist2Date,
			[emgassist_2_amount] = @EmgAssist2Amount,
			[emgassist_2_status] = @EmgAssist2Status,
			[past_shelter] = @PastShelter,
			[past_shelter_date] = @PastShelterDate,
			[past_unsheltered] = @PastUnsheltered,
			[past_unsheltered_date] = @PastUnshelteredDate,
			[past_chemical] = @PastChemical,
			[past_chemical_date] = @PastChemicalDate,
			[past_transitional] = @PastTransitional,
			[past_transitional_date] = @PastTransitionalDate,
			[past_doubled] = @PastDoubled,
			[past_doubled_date] = @PastDoubledDate,
			[past_eviction] = @PastEviction,
			[past_eviction_date] = @PastEvictionDate,
			[past_foreclosure] = @PastForeclosure,
			[past_foreclosure_date] = @PastForeclosureDate,
			[phone_home] = @PhoneHome,
			[phone_work] = @PhoneWork,
			[phone_mobile] = @PhoneMobile,
			[phone_other] = @PhoneOther,
			[employment_frequency] = @EmpFreq,
			[employment_date] = @EmpDate,
			[mfip_day] = @MFIPDay,
			[childsupport_date] = @ChildSupportDate,
			[othersources_date] = @OtherSourcesDate,
			[message] = @Message,
			[flag] = @Flag,
			[organization_id] = @OrganizationId
		WHERE [id] = @ClientId
		SET @ID = @ClientId
	END
END



GO

